CREATE TABLE IF NOT EXISTS associates (associate_id TEXT PRIMARY KEY, associate_name TEXT NOT NULL, team TEXT, shift TEXT, experience_level TEXT, daily_target INTEGER, quality_target REAL);
CREATE TABLE IF NOT EXISTS delivery_partners (partner_id TEXT PRIMARY KEY, partner_name TEXT NOT NULL, city TEXT, region TEXT, partner_status TEXT, onboarding_date TEXT, average_rating REAL, total_completed_deliveries INTEGER, issue_frequency REAL);
CREATE TABLE IF NOT EXISTS cases (case_id TEXT PRIMARY KEY, partner_id TEXT NOT NULL REFERENCES delivery_partners(partner_id), associate_id TEXT NOT NULL REFERENCES associates(associate_id), created_date TEXT, received_time TEXT, issue_type TEXT, issue_subtype TEXT, priority TEXT, sla_minutes REAL, resolution_start_time TEXT, resolution_time TEXT, resolution_minutes REAL, case_status TEXT, resolution_category TEXT, escalation_required INTEGER, escalation_level TEXT, manager_intervention INTEGER DEFAULT 0, sop_resolution_status TEXT DEFAULT 'Resolved', quality_score REAL, quality_status TEXT, sop_followed INTEGER, stakeholder_response_time REAL, stakeholder_response_status TEXT DEFAULT 'Pending', customer_impact TEXT, remarks TEXT, escalation_reason TEXT, escalation_timestamp TEXT, repeated_issue INTEGER DEFAULT 0, elapsed_minutes REAL, remaining_minutes REAL, sla_percentage REAL, sla_status TEXT);
CREATE TABLE IF NOT EXISTS case_updates (update_id INTEGER PRIMARY KEY AUTOINCREMENT, case_id TEXT REFERENCES cases(case_id), updated_by TEXT, updated_at TEXT, update_notes TEXT);
CREATE TABLE IF NOT EXISTS escalations (escalation_id INTEGER PRIMARY KEY AUTOINCREMENT, case_id TEXT REFERENCES cases(case_id), escalation_level TEXT, escalation_reason TEXT, escalation_timestamp TEXT, escalation_status TEXT DEFAULT 'Open');
CREATE TABLE IF NOT EXISTS quality_reviews (review_id INTEGER PRIMARY KEY AUTOINCREMENT, case_id TEXT REFERENCES cases(case_id), quality_score REAL, quality_status TEXT, sop_followed INTEGER, reviewed_at TEXT);
CREATE TABLE IF NOT EXISTS stakeholder_responses (response_id INTEGER PRIMARY KEY AUTOINCREMENT, case_id TEXT REFERENCES cases(case_id), stakeholder_type TEXT, response_required INTEGER, response_sent INTEGER, response_time REAL, response_status TEXT);
CREATE TABLE IF NOT EXISTS daily_operations (operation_date TEXT, associate_id TEXT REFERENCES associates(associate_id), assigned_cases INTEGER, resolved_cases INTEGER, pending_cases INTEGER, sla_compliance REAL, quality_score REAL, escalations INTEGER, average_resolution_time REAL, cases_per_hour REAL, PRIMARY KEY(operation_date, associate_id));
CREATE INDEX IF NOT EXISTS idx_cases_partner ON cases(partner_id); CREATE INDEX IF NOT EXISTS idx_cases_associate ON cases(associate_id); CREATE INDEX IF NOT EXISTS idx_cases_date ON cases(created_date); CREATE INDEX IF NOT EXISTS idx_cases_status ON cases(case_status); CREATE INDEX IF NOT EXISTS idx_cases_priority ON cases(priority); CREATE INDEX IF NOT EXISTS idx_cases_sla ON cases(sla_status);
